development:
  adapter: postgresql
  encoding: unicode
  database: etc_app_development
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: etc_app_test
  pool: 5
  username:
  password:
  host: localhost

staging:
  adapter: postgresql
  encoding: unicode
  database: etc_app_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: etc_app_development
  pool: 5
  username:
  password:
